### ISSUE TITLE
object_finder code review

### ISSUE THREAD

**Issue by scpeters** [osrf/baxter_demos#1]
I'll add my comments about the code to this issue.
1. These computer vision algorithms have lots of parameters. Currently I see a lot of these parameters [hard-coded in object_finder.py](https://github.com/osrf/baxter_demos/blob/master/scripts/object_finder.py#L69-L100) (for variables with sliders, the default value is hard-coded). I like putting parameters in separate files (see the yaml files in the [atlas_teleop tutorial](https://bitbucket.org/osrf/drcsim/src/default/drcsim_tutorials/atlas_teleop/) as an example). Then you can save different configurations in different files, and you don't have to modify the code quite as much.

**Comment by jackieokay** [comment]
I threw all of the hardcoded parameters into config/object_finder.yaml and config/servo_to_object.yaml and loaded them in the nodes using PyYAML. Forthcoming is an option to save slider params into yaml files (or to do away with sliders entirely).
